# Generated by Django 3.2.22 on 2023-11-02 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Home care service', 'Home care services'), ('laboratory services', 'laboratory services'), ('Counselling', 'Counselling'), ('Basic assistance care', 'Basic assistance care'), ('Second opinion', 'Second opinion')], default='Consultation', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('3 PM', '3:00 PM'), ('3:30 PM', '3:30 PM'), ('4 PM', '4:00 PM'), ('4:30 PM', '4:30 PM'), ('5 PM', '5:00 PM'), ('5:30 PM', '5:30 PM'), ('6 PM', '6:00 PM'), ('6:30 PM', '6:30 PM'), ('7 PM', '7:00 PM'), ('7:30 PM', '7:30 PM')], default='3 PM', max_length=10),
        ),
    ]
