# Generated by Django 4.2.1 on 2023-06-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_appointment_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-updated_at', '-created_at'], 'verbose_name_plural': 'Appointment'},
        ),
    ]
