# Generated by Django 4.2.1 on 2023-10-21 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthtips',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
