# Generated by Django 3.2.22 on 2023-10-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Enter active email address', max_length=254, unique=True),
        ),
    ]
