# Generated by Django 3.2.22 on 2023-11-01 23:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20231102_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthtips',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='healthtips',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
