# Generated by Django 4.2.1 on 2023-06-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replycontact',
            name='attachment',
            field=models.FileField(default='empty-profile.png', upload_to='contact-attchments'),
        ),
    ]
