# Generated by Django 4.2.1 on 2023-06-07 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_replycontact_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'ContactUs'},
        ),
        migrations.AlterModelOptions(
            name='replycontact',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'ReplyContact'},
        ),
        migrations.AddField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 23, 45, 59, 39889)),
        ),
        migrations.AddField(
            model_name='replycontact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 7, 23, 45, 59, 40887)),
        ),
        migrations.AlterField(
            model_name='replycontact',
            name='subject',
            field=models.CharField(default='Reply Contacts', max_length=200),
        ),
    ]
