# Generated by Django 4.2.1 on 2023-06-08 21:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_contactus_options_alter_replycontact_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 6, 8, 22, 3, 26, 48979))),
            ],
            options={
                'verbose_name_plural': 'Subscribe',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 22, 3, 26, 46985)),
        ),
        migrations.AlterField(
            model_name='replycontact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 8, 22, 3, 26, 47981)),
        ),
    ]
