# Generated by Django 4.2.1 on 2023-06-09 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_sendnewsletter_alter_contactus_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendnewsletter',
            name='attachment',
            field=models.FileField(default='empty-profile.png', upload_to='newsletter-file'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 13, 5, 31, 597474)),
        ),
        migrations.AlterField(
            model_name='replycontact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 13, 5, 31, 598469)),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 9, 13, 5, 31, 599466)),
        ),
    ]
