# Generated by Django 3.2.22 on 2023-11-09 16:56

import datetime
from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20231105_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 17, 56, 25, 887637)),
        ),
        migrations.AlterField(
            model_name='replycontact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 17, 56, 25, 888664)),
        ),
        migrations.AlterField(
            model_name='sendnewsletter',
            name='letter',
            field=django_quill.fields.QuillField(),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 17, 56, 25, 888664)),
        ),
    ]
