# Generated by Django 3.2.22 on 2023-11-09 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_auto_20231109_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 19, 18, 32, 116622)),
        ),
        migrations.AlterField(
            model_name='replycontact',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 19, 18, 32, 117620)),
        ),
        migrations.AlterField(
            model_name='sendnewsletter',
            name='letter',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 19, 18, 32, 117620)),
        ),
    ]
